import { Oswald, Cormorant_Garamond } from 'next/font/google'

import { AuthProvider } from '@/context'

import './globals.css'

const oswald = Oswald({ subsets: ['latin'], variable: '--font-oswald' })
const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-cormorant',
})

export const metadata = {
  title: 'The Country Buthcher',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${oswald.variable} ${cormorant.variable} font-oswald bg-secondary`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
