import Navbar from '@/components/Navbar'
import './globals.css'
import { Oswald, Cormorant_Garamond } from 'next/font/google'
import Footer from '@/components/Footer'
import Map from '@/components/Map'
import ScrollToTop from '@/components/ScrollToTop'

const oswald = Oswald({ subsets: ['latin'], variable: '--font-oswald' })
const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-cormorant',
})

export const metadata = {
  title: 'The Country Buthcher',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${oswald.variable} ${cormorant.variable} font-oswald bg-secondary`}
      >
        <Navbar />
        {children}
        <ScrollToTop />
        <Map />
        <Footer />
      </body>
    </html>
  )
}
